### ISSUE TITLE
ColourBoredom assumes running on dev's computer

### ISSUE THREAD

**Issue by NotADinosaur** [KJP12/Because-I-can#1]
Hi. Sorry to make an issue for something that hasn’t been touched in 3 years but oh well lol, might as well give it a try.
So, I was bored and was looking through random peoples github profiles to see if there was anything that might be interesting and this "colourboredom" caught my eye because I like colourful things. I got it to compile and tried random flags until it accepted them, but it seems to be looking for some file on your computer? and I was wondering if I could fix that. Like, just change the path and put that file on my computer or something? 
Anyways, any help would be appreciated although I don’t really expect any for something like this. 
~~yes, I try to get random old github projects to work when I’m bored. No, I don’t know why.~~

**Comment by Ampflower** [comment]
Oh, sorry, didn't realise that there was a reference to a file on my system when I uploaded it some time ago.

The following could be changed if you'd like to set it to a file you do have (or change it to use the arguments from `main`)
https://github.com/KJP12/Because-I-can/blob/a239626001f2010dbaba810c583848b767ff0476/ColourBoredom/src/main/java/net/kjp12/doot/Main.java#L27

You probably could swap it out for just `./<some randomly generated integer>.gif` too, since it seems to just create the file anyways.

**Comment by NotADinosaur** [comment]
Was a bit busy but just got around to trying that fix and yep, it works now. Or, at least somewhat: the file is only 1 byte and doesn’t contain anything. I’m guessing it’s because of the flags I’m using just being random numbers, so what should I be using for those? Sorry to bother you again.

**Comment by Ampflower** [comment]
One byte is an odd one; perhaps there's more bugs that may need fixing; by chance, could you send which arguments you gave it?

**Comment by NotADinosaur** [comment]
Sure. I just gave it random numbers because it seemed to accept them and I wasn’t sure what to put. For example, `-3 -2 -4` or `-700 -400 -1000`

**Comment by Ampflower** [comment]
Ah, that'd do it; it expects positive integers, there's just no code to enforce that.

**Comment by NotADinosaur** [comment]
Oh, I see. I thought it would want dashes since most programs I’ve seen do

**Comment by Ampflower** [comment]
Fixed as part of rewriting history.
